GridFilterButtons
linz/step-ag-grid pull request #228
Opened 2023-02-21 21:09 UTC by matttdawson

```
<GridFilterButtons<ITestRow>
  options={[
    {
      label: "All",
      defaultSelected: true,
    },
    {
      label: "< 30",
      filter: (row) => row.age < 30,
    },
  ]}
/>
```
![image](https://user-images.githubusercontent.com/89495499/220458918-3c6a7804-dbf9-4292-95c0-e9672621e48a.png)

2023-02-21 21:45 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +              style={{ whiteSpace: "nowrap" }}
I don't like this.  What if they want to wrap.

2023-02-21 22:12 UTC, jfee-linz requested changes

2023-02-21 22:12 UTC, jfee-linz commented on src/components/gridFilter/GridFilterButtons.tsx
> +              style={{ whiteSpace: "nowrap" }}
Can nowrap be set using a default css class that can be restyled?  Or maybe an optional `labelRenderer(option, {isSelected, setSelected})` property to override the LuiButton (using radio/similar)?

2023-02-21 22:12 UTC, jfee-linz commented on src/components/gridFilter/GridFilterButtons.tsx
> +          <>
is the fragment needed here?

2023-02-21 22:12 UTC, jfee-linz commented on src/components/gridFilter/GridFilterButtons.tsx
> +  const [selectedOption, setSelectedOption] = useState(options.find((option) => option.defaultSelected));
should this default to the first item if no `defaultSelected` is configured?

2023-02-21 22:12 UTC, jfee-linz commented on src/components/gridFilter/GridFilterButtons.tsx
> +    filter?: GridFilterExternal<RowType>;
I'm a fan of alphabetizing properties

2023-02-21 22:12 UTC, jfee-linz commented on src/contexts/GridContextProvider.tsx
> +  const externalFilters = useRef<GridFilterExternal<any>[]>([]);
What about making the context provider templated `<T = unknown>` ?

2023-02-22 00:11 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +    filter?: GridFilterExternal<RowType>;
Hmm, I usually put them in order of importance.  In this case I should have put label, filter, defaultSelected. I'll think on it.

2023-02-22 00:11 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +          <>
Nope :)

2023-02-22 00:11 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +  const [selectedOption, setSelectedOption] = useState(options.find((option) => option.defaultSelected));
Sure thing.

2023-02-22 00:25 UTC, matttdawson commented on src/contexts/GridContextProvider.tsx
> +  const externalFilters = useRef<GridFilterExternal<any>[]>([]);
Fixed.

2023-02-22 00:25 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +    filter?: GridFilterExternal<RowType>;
Done

2023-02-22 00:25 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +  const [selectedOption, setSelectedOption] = useState(options.find((option) => option.defaultSelected));
Done

2023-02-22 00:25 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +          <>
Done

2023-02-22 00:44 UTC, matttdawson commented on src/components/gridFilter/GridFilterButtons.tsx
> +              style={{ whiteSpace: "nowrap" }}
I've added luiButtonProps prop

2023-02-22 00:59 UTC, jfee-linz approved these changes
Looks good

2023-02-22 02:34 UTC, merged